//! Cross-language contract tests.
//!
//! The golden document is generated by the Dart reference implementation
//! (`packages/flutter_sangfor_atrust/test/native_fixtures_test.dart`) and is the
//! same file the Swift core is checked against. If Dart changes the wire format
//! its own test fails and the fixtures are regenerated; if Rust drifts from
//! them, this file fails. Three implementations, one source of truth.

use std::collections::BTreeMap;
use std::path::PathBuf;

use sangfor_core::crypto;
use sangfor_core::json::{self, Json};
use sangfor_core::l3::{self, AuthRequest, IpInfo, ProcessInfo};
use sangfor_core::packet::{self, build_packet_meta, build_tcp, flag, TcpPacketParams};
use sangfor_core::plan::{parse_endpoint, SessionPlan};
use sangfor_core::route::RouteTable;
use sangfor_core::tcp_tunnel::{self, AuthRequest as TcpAuthRequest};

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../packages/flutter_sangfor/test/fixtures/native_atrust.json")
}

fn fixture() -> serde_json::Value {
    let raw = std::fs::read(fixture_path()).expect(
        "missing native_atrust.json; regenerate it with \
         UPDATE_NATIVE_FIXTURES=1 flutter test test/native_fixtures_test.dart",
    );
    serde_json::from_slice(&raw).expect("the fixture is valid JSON")
}

fn text(value: &serde_json::Value, path: &[&str]) -> String {
    let mut node = value;
    for key in path {
        node = node
            .get(key)
            .unwrap_or_else(|| panic!("fixture is missing {}", path.join(".")));
    }
    node.as_str()
        .unwrap_or_else(|| panic!("fixture {} is not a string", path.join(".")))
        .to_string()
}

fn int(value: &serde_json::Value, path: &[&str]) -> i64 {
    let mut node = value;
    for key in path {
        node = node
            .get(key)
            .unwrap_or_else(|| panic!("fixture is missing {}", path.join(".")));
    }
    node.as_i64()
        .unwrap_or_else(|| panic!("fixture {} is not an integer", path.join(".")))
}

fn unhex(text: &str) -> Vec<u8> {
    crypto::unhex(text).expect("fixture hex decodes")
}

const PROCESS_PATH: &str = "/var/mobile/Containers/Bundle/Application/Luotopia.app";

fn process_info() -> ProcessInfo {
    ProcessInfo {
        name: "Luotopia".to_string(),
        path: PROCESS_PATH.to_string(),
        platform: "iOS".to_string(),
    }
}

fn auth_request() -> AuthRequest {
    AuthRequest {
        sid: "REDACTED_SID".to_string(),
        app_id: "app-42".to_string(),
        url: "tcp:203.0.113.7:443".to_string(),
        device_id: "REDACTED_DEVICE".to_string(),
        connection_id: "REDACTED_CONNECTION".to_string(),
        lang: "zh-CN".to_string(),
        conntrack_hash: 7,
        ip: IpInfo {
            atype: 0x0800,
            protocol: packet::TCP,
            destination_address: "203.0.113.7".to_string(),
            destination_port: 443,
            source_address: "10.0.0.42".to_string(),
            source_port: 51000,
        },
        proc_hash: None,
        app_token: None,
        rc_applied_info: 0,
        process: Some(process_info()),
        domain: None,
    }
}

fn tcp_auth_request(fingerprint: &str) -> TcpAuthRequest {
    TcpAuthRequest {
        sid: "REDACTED_SID".to_string(),
        app_id: "app-42".to_string(),
        url: "tcp://vpn.example.test:443".to_string(),
        device_id: "REDACTED_DEVICE".to_string(),
        connection_id: "REDACTED_CONNECTION".to_string(),
        proc_hash: fingerprint.to_string(),
        user_name: "alice".to_string(),
        lang: "zh-CN".to_string(),
        dest_addr: "vpn.example.test:443".to_string(),
        dest_ip: Some("203.0.113.7".to_string()),
        rc_applied_info: 0,
        process: Some(process_info()),
    }
}

#[test]
fn sha256_and_hmac_match_the_reference() {
    let fixture = fixture();
    assert_eq!(
        crypto::hex_lower(&crypto::sha256(&[])),
        text(&fixture, &["sha256", "empty"])
    );
    assert_eq!(
        crypto::hex_lower(&crypto::sha256_str("abc")),
        text(&fixture, &["sha256", "abc"])
    );
    let long: Vec<u8> = (0..1000u32).map(|index| (index % 251) as u8).collect();
    assert_eq!(
        crypto::hex_lower(&crypto::sha256(&long)),
        text(&fixture, &["sha256", "long"]),
        "multi-block padding"
    );
    assert_eq!(
        crypto::hex_lower(&crypto::hmac_sha256(b"abc", b"abc")),
        text(&fixture, &["hmacSha256", "abcKeyAbcData"])
    );
}

#[test]
fn the_process_fingerprint_matches() {
    let fixture = fixture();
    assert_eq!(
        crypto::process_fingerprint(PROCESS_PATH),
        text(&fixture, &["processFingerprint"])
    );
}

#[test]
fn the_anti_mitm_digest_uses_the_gateway_salt() {
    let fixture = fixture();
    let der = base64_decode(&text(&fixture, &["certificateDigest", "derBase64"]));
    assert_eq!(
        crypto::certificate_digest(&der),
        text(&fixture, &["certificateDigest", "digest"])
    );
    assert!(
        crypto::certificate_matches(
            &der,
            &[text(&fixture, &["certificateDigest", "digest"]).to_lowercase()]
        ),
        "pin comparison ignores case"
    );
    assert!(!crypto::certificate_matches(&der, &[]));
}

fn base64_decode(text: &str) -> Vec<u8> {
    use base64::Engine as _;
    base64::engine::general_purpose::STANDARD
        .decode(text)
        .expect("fixture base64 decodes")
}

#[test]
fn canonical_json_matches_dart_byte_for_byte() {
    let fixture = fixture();
    let value = Json::object(vec![
        ("quote".into(), Json::string("a\"b")),
        ("backslash".into(), Json::string("a\\b")),
        ("tab".into(), Json::string("a\tb")),
        ("newline".into(), Json::string("a\nb")),
        ("carriageReturn".into(), Json::string("a\rb")),
        ("backspace".into(), Json::string("a\u{8}b")),
        ("formFeed".into(), Json::string("a\u{c}b")),
        ("control".into(), Json::string("a\u{1}b\u{1f}b")),
        ("delete".into(), Json::string("a\u{7f}b")),
        ("nonAscii".into(), Json::string("a\u{e9}\u{4e2d}b")),
        ("int".into(), Json::Int(7)),
        ("negativeInt".into(), Json::Int(-12)),
        ("true".into(), Json::Bool(true)),
        ("false".into(), Json::Bool(false)),
        ("null".into(), Json::Null),
        (
            "array".into(),
            Json::Array(vec![
                Json::Int(1),
                Json::string("two"),
                Json::object(vec![("three".into(), Json::Int(3))]),
            ]),
        ),
        ("emptyObject".into(), Json::object(vec![])),
        ("emptyArray".into(), Json::Array(vec![])),
    ]);
    assert_eq!(
        json::encode_to_string(&value),
        text(&fixture, &["jsonEscaping"])
    );
}

#[test]
fn l3_flow_auth_body_and_signature_match() {
    let fixture = fixture();
    let sign_key = unhex(&text(&fixture, &["signKeyHex"]));
    let request = auth_request();
    assert_eq!(
        String::from_utf8(request.unsigned_body()).expect("utf8"),
        text(&fixture, &["l3", "authUnsignedJson"])
    );
    assert_eq!(
        request.signature(&sign_key),
        text(&fixture, &["l3", "authSignature"])
    );
    assert_eq!(
        crypto::hex_lower(&request.frame(&sign_key).expect("frame")),
        text(&fixture, &["l3", "authRequestFrameHex"])
    );
}

#[test]
fn l3_request_frames_match() {
    let fixture = fixture();
    assert_eq!(
        crypto::hex_lower(&l3::auth_tunnel_request("REDACTED_SID").expect("frame")),
        text(&fixture, &["l3", "authTunnelRequestHex"])
    );
    let sample = unhex(&text(&fixture, &["packet", "sampleHex"]));
    assert_eq!(
        crypto::hex_lower(&l3::data_request("tok-1", &sample).expect("frame")),
        text(&fixture, &["l3", "dataRequestFrameHex"])
    );
    assert_eq!(
        crypto::hex_lower(&l3::heartbeat_request()),
        text(&fixture, &["l3", "heartbeatFrameHex"])
    );
    for (key, expected) in [("ipv4", 6usize), ("ipv6", 18), ("dual", 22)] {
        let _ = expected;
        let header = match key {
            "ipv4" => [0x05, 0x00, 0x00, 0x01],
            "ipv6" => [0x05, 0x00, 0x00, 0x04],
            _ => [0x05, 0x00, 0x00, 0x05],
        };
        assert_eq!(
            l3::parse_vip_header(&header).expect("vip header") as i64,
            int(&fixture, &["l3", "vipHeaderLengths", key]),
            "{key} VIP payload length"
        );
    }
}

#[test]
fn the_handshake_parser_consumes_a_fragmented_sequence() {
    let fixture = fixture();
    let response = unhex(&text(&fixture, &["l3", "handshakeResponseHex"]));
    let mut parser = l3::HandshakeParser::new();
    let mut result = None;
    for index in 0..response.len() {
        result = parser.push(&response[index..index + 1]).expect("parses");
        if result.is_some() {
            break;
        }
    }
    let (parsed, leftover) = result.expect("the handshake completes");
    assert_eq!(
        parsed.virtual_ip,
        vec![text(&fixture, &["l3", "handshakeVip"])]
    );
    assert_eq!(parsed.device_id.as_deref(), Some("REDACTED_DEVICE"));
    assert!(leftover.is_empty());

    // Leftover bytes of the next frame survive the handshake.
    let mut parser = l3::HandshakeParser::new();
    let mut combined = response.clone();
    combined.extend_from_slice(&l3::heartbeat_request());
    let (parsed, leftover) = parser.push(&combined).expect("parses").expect("complete");
    assert_eq!(parsed.virtual_ip.len(), 1);
    assert_eq!(leftover, l3::heartbeat_request());
}

#[test]
fn the_frame_decoder_survives_chunk_boundaries() {
    let fixture = fixture();
    let sample = unhex(&text(&fixture, &["packet", "sampleHex"]));
    let mut combined = vec![0x05, 0x95, 0x00, 0x00];
    let mut data = vec![0x05, 0x94];
    data.extend_from_slice(&(sample.len() as u16).to_be_bytes());
    data.extend_from_slice(&sample);
    combined.extend_from_slice(&data);

    let mut decoder = l3::FrameDecoder::new();
    let mut frames = Vec::new();
    for index in 0..combined.len() {
        frames.extend(decoder.push(&combined[index..index + 1]).expect("decodes"));
    }
    assert_eq!(frames.len(), 2);
    assert_eq!(frames[0].command, l3::Command::HeartbeatResponse);
    assert_eq!(frames[1].command, l3::Command::DataResponse);
    assert_eq!(frames[1].payload, sample);
}

#[test]
fn tcp_tunnel_frames_and_signatures_match() {
    let fixture = fixture();
    let sign_key = unhex(&text(&fixture, &["signKeyHex"]));
    let fingerprint = text(&fixture, &["processFingerprint"]);
    let request = tcp_auth_request(&fingerprint);
    assert_eq!(
        String::from_utf8(request.unsigned_body()).expect("utf8"),
        text(&fixture, &["tcpTunnel", "unsignedJson"])
    );
    assert_eq!(
        request.signature(&sign_key),
        text(&fixture, &["tcpTunnel", "signature"])
    );
    assert_eq!(
        crypto::hex_lower(
            &tcp_tunnel::protocol::handshake_message(
                &request,
                &sign_key,
                "vpn.example.test",
                443,
                false
            )
            .expect("handshake")
        ),
        text(&fixture, &["tcpTunnel", "handshakeHex"])
    );
    assert_eq!(
        crypto::hex_lower(
            &tcp_tunnel::protocol::destination_message("vpn.example.test", 443, false)
                .expect("destination")
        ),
        text(&fixture, &["tcpTunnel", "destinationDomainHex"])
    );
    assert_eq!(
        crypto::hex_lower(
            &tcp_tunnel::protocol::destination_message("203.0.113.7", 443, false)
                .expect("destination")
        ),
        text(&fixture, &["tcpTunnel", "destinationIpv4Hex"])
    );
    assert_eq!(
        crypto::hex_lower(&tcp_tunnel::protocol::data_frame(&[1, 2, 3, 4, 5]).expect("frame")),
        text(&fixture, &["tcpTunnel", "dataFrameHex"])
    );
    assert_eq!(
        crypto::hex_lower(&tcp_tunnel::protocol::eof_frame()),
        text(&fixture, &["tcpTunnel", "eofFrameHex"])
    );

    let hello = unhex(&text(&fixture, &["tcpTunnel", "serverResponseHex"]));
    let response = tcp_tunnel::protocol::parse_server_response(&hello)
        .expect("parses")
        .expect("complete");
    assert_eq!(
        response.auth_code,
        int(&fixture, &["tcpTunnel", "serverResponse", "authCode"])
    );
    assert_eq!(
        response.connect_status as i64,
        int(&fixture, &["tcpTunnel", "serverResponse", "connectStatus"])
    );
    assert_eq!(
        response.consumed as i64,
        int(&fixture, &["tcpTunnel", "serverResponse", "consumed"])
    );

    // The incremental decoder reaches the same answer one byte at a time.
    let mut decoder = tcp_tunnel::HandshakeDecoder::new();
    let mut leftover = None;
    for index in 0..hello.len() {
        leftover = decoder.push(&hello[index..index + 1]).expect("parses");
        if decoder.response().is_some() {
            break;
        }
    }
    assert_eq!(decoder.response(), Some(&response));
    assert!(leftover.expect("leftover").is_empty());
}

#[test]
fn the_packet_codec_matches_dart_byte_for_byte() {
    let fixture = fixture();
    let sample = unhex(&text(&fixture, &["packet", "sampleHex"]));
    let meta = build_packet_meta(&sample).expect("the sample parses");
    assert_eq!(
        i64::from(meta.atype),
        int(&fixture, &["packet", "meta", "atype"])
    );
    assert_eq!(
        i64::from(meta.protocol),
        int(&fixture, &["packet", "meta", "protocol"])
    );
    assert_eq!(
        meta.source_text(),
        text(&fixture, &["packet", "meta", "sourceAddress"])
    );
    assert_eq!(
        i64::from(meta.source_port),
        int(&fixture, &["packet", "meta", "sourcePort"])
    );
    assert_eq!(
        meta.destination_text(),
        text(&fixture, &["packet", "meta", "destinationAddress"])
    );
    assert_eq!(
        i64::from(meta.destination_port),
        int(&fixture, &["packet", "meta", "destinationPort"])
    );

    let mut doubled = sample.clone();
    doubled.extend_from_slice(&sample);
    let (packets, remaining) = packet::split_incoming_packets(&doubled).expect("splits");
    assert_eq!(packets.len(), 2);
    assert!(remaining.is_empty());
    assert_eq!(packets[0], sample.as_slice());

    // A truncated trailing packet stays buffered instead of being dropped.
    let partial = &doubled[..sample.len() + 5];
    let (packets, remaining) = packet::split_incoming_packets(partial).expect("splits");
    assert_eq!(packets.len(), 1);
    assert_eq!(remaining.len(), 5);

    let params = TcpPacketParams {
        source: packet::parse_ipv4("203.0.113.7").expect("ipv4"),
        destination: packet::parse_ipv4("10.0.0.42").expect("ipv4"),
        source_port: 443,
        destination_port: 51000,
        sequence: 0x1122_3344,
        acknowledgment: 0x5566_7788,
        flags: flag::SYN | flag::ACK,
        window: 64240,
        identification: 7,
        ttl: 64,
        mss: Some(1400),
    };
    let built = build_tcp(&params, &[1, 2, 3, 4, 5]);
    assert_eq!(
        crypto::hex_lower(&built),
        text(&fixture, &["packet", "builtTcpHex"])
    );

    let bare = build_tcp(
        &TcpPacketParams {
            source: params.source,
            destination: params.destination,
            source_port: 443,
            destination_port: 51000,
            sequence: 1,
            acknowledgment: 2,
            flags: flag::ACK,
            window: 65535,
            identification: 9,
            ttl: 64,
            mss: None,
        },
        &[],
    );
    assert_eq!(
        crypto::hex_lower(&bare),
        text(&fixture, &["packet", "builtTcpNoPayloadHex"])
    );

    // A packet we built verifies against its own stored checksums.
    assert_eq!(
        packet::ipv4_header_checksum(&built),
        u16::from_be_bytes([built[10], built[11]])
    );
    let mut zeroed = built.clone();
    let stored = u16::from_be_bytes([zeroed[36], zeroed[37]]);
    zeroed[36] = 0;
    zeroed[37] = 0;
    assert_eq!(packet::tcp_checksum(&zeroed, 20), stored);
}

#[test]
fn sequence_arithmetic_wraps() {
    assert_eq!(packet::sequence_add(0xffff_ffff, 2), 1);
    assert_eq!(packet::sequence_difference(0xffff_ffff, 1), 2);
    assert_eq!(packet::sequence_difference(1, 0xffff_ffff), -2);
    assert_eq!(packet::sequence_difference(5, 5), 0);
}

#[test]
fn the_session_plan_decodes_the_dart_document() {
    let fixture = fixture();
    let document = text(&fixture, &["sessionPlan"]);
    let plan = SessionPlan::decode(document.as_bytes()).expect("the plan decodes");
    assert_eq!(plan.sid, "REDACTED_SID");
    assert_eq!(plan.device_id, "REDACTED_DEVICE");
    assert_eq!(plan.connection_id, "REDACTED_CONNECTION");
    assert_eq!(plan.username, "alice");
    assert_eq!(plan.lang, "zh-CN");
    assert_eq!(plan.process_platform, "iOS");
    assert_eq!(plan.sign_key().expect("key").len(), 32);
    assert_eq!(
        plan.sign_key().expect("key"),
        unhex(&text(&fixture, &["signKeyHex"]))
    );
    assert_eq!(plan.major_node_group, "group-1");
    assert_eq!(plan.virtual_address.as_deref(), Some("10.0.0.42"));
    assert_eq!(plan.dns_servers, vec!["203.0.113.53".to_string()]);
    assert_eq!(plan.fingerprint(), text(&fixture, &["processFingerprint"]));
    assert_eq!(plan.routes.len(), 3);

    let endpoint = plan.node_endpoint("group-1").expect("endpoint");
    assert_eq!(endpoint.0, "203.0.113.9");
    assert_eq!(endpoint.1, 441);
    assert_eq!(
        plan.node_endpoint("missing").expect("falls back").0,
        "203.0.113.9",
        "an unknown group falls back to the major group"
    );
    assert_eq!(plan.dial_host("203.0.113.7"), Some("vpn.example.test"));

    // The decoded routes drive the same decisions the Dart side makes.
    let table = plan.route_table();
    let l3_address = packet::parse_ipv4("10.1.2.3").expect("ipv4");
    assert_eq!(
        table
            .match_l3(l3_address, "tcp", 443)
            .map(|route| route.app_id.as_str()),
        Some("app-l3"),
        "the L3-preferred resource is forwardable as raw IP"
    );
    let tcp_address = packet::parse_ipv4("10.9.1.2").expect("ipv4");
    assert!(
        table.match_l3(tcp_address, "tcp", 443).is_none(),
        "the TCP-tunnel resource is not forwardable as raw IP"
    );
    assert_eq!(
        table
            .match_tcp("10.9.1.2", 443, true)
            .map(|route| route.app_id.as_str()),
        Some("app-tcp")
    );
    assert_eq!(
        table
            .match_tcp(plan.dial_host("203.0.113.7").expect("alias"), 443, true)
            .map(|route| route.app_id.as_str()),
        Some("app-domain"),
        "a domain resource matches through its alias"
    );
    assert!(
        table.match_tcp("203.0.113.7", 443, true).is_none(),
        "a resolved address does not match a domain resource on its own"
    );
}

#[test]
fn endpoint_parsing_defaults_the_port() {
    assert_eq!(
        parse_endpoint("203.0.113.9:441"),
        Some(("203.0.113.9".to_string(), 441))
    );
    assert_eq!(
        parse_endpoint("203.0.113.9"),
        Some(("203.0.113.9".to_string(), 441))
    );
    assert_eq!(
        parse_endpoint("[2001:db8::1]:443"),
        Some(("2001:db8::1".to_string(), 443))
    );
    assert_eq!(
        parse_endpoint("[2001:db8::1]"),
        Some(("2001:db8::1".to_string(), 441))
    );
}

#[test]
fn route_matching_covers_every_host_shape() {
    let table = RouteTable::new(vec![
        sangfor_core::route::Route {
            host: "10.0.0.0/8".to_string(),
            protocol: "tcp".to_string(),
            port_min: 0,
            port_max: 65535,
            app_id: "cidr".to_string(),
            node_group_id: "g".to_string(),
            addr_pretend: false,
            enable_tcp_pref_l3: true,
        },
        sangfor_core::route::Route {
            host: "10.9.0.5~10.9.0.20".to_string(),
            protocol: "all".to_string(),
            port_min: 0,
            port_max: 65535,
            app_id: "range".to_string(),
            node_group_id: "g".to_string(),
            addr_pretend: false,
            enable_tcp_pref_l3: true,
        },
        sangfor_core::route::Route {
            host: "*.whu.edu.cn".to_string(),
            protocol: "tcp".to_string(),
            port_min: 443,
            port_max: 443,
            app_id: "domain".to_string(),
            node_group_id: "g".to_string(),
            addr_pretend: true,
            enable_tcp_pref_l3: false,
        },
    ]);
    let cidr = packet::parse_ipv4("10.9.1.2").expect("ipv4");
    assert!(table.match_l3(cidr, "tcp", 443).is_some());
    let in_range = packet::parse_ipv4("10.9.0.7").expect("ipv4");
    assert!(table.match_l3(in_range, "udp", 53).is_some());
    let outside = packet::parse_ipv4("11.9.1.2").expect("ipv4");
    assert!(table.match_l3(outside, "tcp", 443).is_none());
    assert!(table.match_tcp("ids.whu.edu.cn", 443, false).is_some());
    assert!(
        table.match_tcp("whu.edu.cn", 443, false).is_none(),
        "a wildcard does not cover the apex"
    );
    assert!(table.match_tcp("ids.whu.edu.cn", 80, false).is_none());
}

#[test]
fn the_plan_schema_is_stable_across_languages() {
    // A document Dart writes must round-trip through Rust without losing
    // fields, including the optional ones.
    let fixture = fixture();
    let document = text(&fixture, &["sessionPlan"]);
    let plan = SessionPlan::decode(document.as_bytes()).expect("decodes");
    let reencoded = serde_json::to_value(&plan).expect("encodes");
    let original: serde_json::Value = serde_json::from_str(&document).expect("parses");
    let normalize = |value: &serde_json::Value| -> BTreeMap<String, String> {
        value
            .as_object()
            .expect("object")
            .iter()
            .map(|(key, value)| (key.clone(), value.to_string()))
            .collect()
    };
    assert_eq!(
        normalize(&original),
        normalize(&reencoded),
        "every field survives the round trip with the same name"
    );
}
